### ISSUE TITLE
Overaggressive definition of BOOST_NO_CXX11_HDR_MUTEX (libstdc++, Mac OS)

### ISSUE THREAD

**Issue by francoisk** [boostorg/config#399] opened 2021-08-24 10:01 UTC
Boost.Config defines `BOOST_NO_CXX11_HDR_MUTEX`  if libstdc++ does not support timed mutexes (which is currently the case on Mac OS because `_POSIX_TIMEOUTS` is `-1` on that platform).

But there are many other useful constructs in `<mutex>` besides `timed_mutex`.

This also causes other Boost libraries to make drastic decisions such as Boost.Regex going into C++03 mode and selecting its v4 instead of v5 headers, and Boost.Context using Boost.Thread instead of `<mutex>`, despite the fact that neither of these libraries even use any timed mutexes (as far as I can tell).

Does this not seem a bit too aggressive?

**Comment by jzmaddock** [comment] 2021-09-10 10:52
BOOST_NO_CXX11_HDR_MUTEX is an all or nothing macro - and timed mutexes are not an optional part of that header.

However, looking at the latest MacOS runs here: https://github.com/boostorg/config/runs/3565734434?check_suite_focus=true, and looking at the config_info output in C++11 mode or later, I see that BOOST_NO_CXX11_HDR_MUTEX is *NOT* defined.  This is with "Apple LLVM 12.0.0 (clang-1200.0.32.29)" BTW.

**Comment by francoisk** [comment] 2021-09-16 06:37
> BOOST_NO_CXX11_HDR_MUTEX is an all or nothing macro - and timed mutexes are not an optional part of that header.

You could add a finer-grained macro like BOOST_NO_CXX11_TIMED_MUTEX. This is what libstdc++ appears to have done: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=50196#c1. However I hear you about `<mutex>` being a complete unit.

> However, looking at the latest MacOS runs here: https://github.com/boostorg/config/runs/3565734434 check_suite_focus=true, and looking at the config_info output in C++11 mode or later, I see that BOOST_NO_CXX11_HDR_MUTEX is NOT defined. This is with "Apple LLVM 12.0.0 (clang-1200.0.32.29)" BTW.

Right, the problem is only with libstdc++ on Mac OS.

**Comment by barracuda156** [comment] 2022-10-19 04:45
This should be fixed. As it is, it breaks the build with GCC: https://github.com/boostorg/json/issues/774

**Comment by pdimov** [comment] 2022-10-19 07:59
Yeah, Boost.System disables `<system_error>` interoperability when `BOOST_NO_CXX11_HDR_MUTEX` is defined, because it needs to use `std::mutex` in that case. I'm not sure why timed mutexes are deemed so relevant as to disable the entire header, but even if we suppose they are for some reason, how can I recover from this? There's no way to know that Boost.Config has decided to disable `<mutex>` support because of the absence of timed mutexes, and I don't want to drop my support for `<system_error>` in that case.

**Comment by pdimov** [comment] 2022-10-19 10:50
The amusing thing is that libstdc++ actually seems to have a `timed_mutex` even when `_GTHREAD_USE_MUTEX_TIMEDLOCK` is not defined since [this 2015 commit](https://github.com/gcc-mirror/gcc/commit/f16081c2c6fb60a69195c3810fd88ed263757d21) which seems to be in GCC 6. So Config is totally in the wrong here, not just kind of wrong.

**Comment by jzmaddock** [comment] 2022-10-19 11:04
@pdimov : care to file a PR?

Or we could have a separate macro for <system_error> ?

BTW if a check for an incomplete <mutex> is good enough then using __has_include plus a check on C++ version is probably good enough?  I'm confused why you're checking for <mutex> in that case?

**Comment by pdimov** [comment] 2022-10-19 11:24
I don't understand your questions, sorry.

**Comment by pdimov** [comment] 2022-10-19 11:33
I am checking the macro `BOOST_NO_CXX11_HDR_MUTEX`

https://github.com/boostorg/system/blob/9a6d79b84147854aa919644b56b8553f5a2bedb8/include/boost/system/detail/config.hpp#L22

because I need to include the `<mutex>` header

https://github.com/boostorg/system/blob/9a6d79b84147854aa919644b56b8553f5a2bedb8/include/boost/system/detail/error_category_impl.hpp#L104

and then use `std::mutex`

https://github.com/boostorg/system/blob/9a6d79b84147854aa919644b56b8553f5a2bedb8/include/boost/system/detail/error_category_impl.hpp#L119

The problem is that `BOOST_NO_CXX11_HDR_MUTEX` is getting defined for libstdc++ on MacOS here

https://github.com/boostorg/config/blob/2543ff139707a32cc421b62c9d65bb4d9c965b3e/include/boost/config/stdlib/libstdcpp3.hpp#L464

even though it has a `<mutex>` header, with a functional `std::mutex`.

Furthermore, it looks like libstdc++ since GCC 6 has a fully functional `<mutex>` on MacOS, complete with timed mutexes.

**Comment by jzmaddock** [comment] 2022-10-19 14:42
Got it.  Sorry I thought you were only use \<system_error\>.

I'm away travelling for a few days now, but I'll try and get this when I get back.

**Comment by grisumbras** [comment] 2022-11-05 14:14
Hi, any updates on this?

**Comment by pdimov** [comment] 2022-11-06 15:16
Ping? Can we please get this fixed for 1.81?

**Comment by barracuda156** [comment] 2022-11-06 18:11
> Ping? Can we please get this fixed for 1.81?

And hopefully backported to 1.80, so we don’t end up with one version of Boost broken on a bunch of systems.

**Comment by jzmaddock** [comment] 2022-11-07 19:16
OK the referenced PR is nearly there, but there are testing failures with gcc-11 on MacOS 12: https://github.com/boostorg/config/actions/runs/3412675779/jobs/5678491487, anyone able to figure out what the issue is?  Gcc-11 on MacOS 11 is fine BTW.

**Comment by pdimov** [comment] 2022-11-07 19:45
Looks like it's just crashing without any other information. It's probably a preexisting problem not caused by the patch.

**Comment by jzmaddock** [comment] 2022-11-08 13:16
>Looks like it's just crashing without any other information. It's probably a preexisting problem not caused by the patch.

Oh sure, it would just be nice to fix things while I'm here.

**Closed** 2022-11-09 12:51 UTC
